# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "raw-array"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Raw Array Container"
homepage.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
cfg-if = { workspace = true }
sys = { workspace = true }
verus_stub = { workspace = true }

[features]
default = []
std = ["sys/std"]
# Enable Verus verification for this crate.
verus = ["verus_stub/disable", "sys/verus"]

[build-dependencies]

[package.metadata.verus]
verify = true

[lints]
workspace = true
