# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "verus_macro_stub"
version.workspace = true
edition.workspace = true
license-file.workspace = true
authors.workspace = true
homepage.workspace = true

[lib]
proc-macro = true

[dependencies]

[lints]
workspace = true
